### ISSUE TITLE
Regression 0.7.2 -> 0.7.3

### ISSUE THREAD

**Issue by RomeoV** [JuliaSIMD/Polyester.jl#127]
I made a little package that speeds up (dense) x (sparse) matmul (https://github.com/RomeoV/ThreadedDenseSparseMul.jl) and (happened to be) on Polyester `0.5` during development.

When updating (and bisecting) the Polyester version to the latest, I've noticed that Polyester 0.7.2 -> 0.7.3 broke my package functionality, such that the loop below maxes out my cpu but never finishes.

The loop is simply
```julia
import SparseArrays: SparseMatrixCSC, mul!; import SparseArrays
import Polyester: @batch

function mymul!(C::AbstractMatrix, A::AbstractMatrix, B::SparseMatrixCSC, α::Number, β::Number)
    @batch for j in axes(B, 2)
        C[:, j] .*= β
        C[:, j] .+= A * (α.*B[:, j])
    end
    return C
end
```

You can test it out with 
```julia
julia> N, K, M = 1_000, 2_000, 30_000;

julia> A = rand(N, K); B = sprand(K, M, 0.05); C = similar(A, (N, M));

julia> mymul!(C, A, B, true, false)
```

Again, this computation doesn't finish with Polyester version `>= 0.7.3` (but finishes very quickly with `<0.7.3`) and when we `Ctrl-C` we always find the cpu to currently eval 
```
ERROR: InterruptException:
Stacktrace:
 [1] getindex(x::SparseMatrixCSC{Float64, Int64}, ::Colon, j::Int64)
   @ SparseArrays ~/.julia/juliaup/julia-1.10.0-rc1+0.x64.linux.gnu/share/julia/stdlib/v1.10/SparseArrays/src/sparsevector.jl:629
```

I saw that `0.7.3` changed a few dependencies around, so probably the problem got introduced somewhere there.
For now, I'll just restrict my package `[compat]`, but maybe this points at a problem deeper down...
Any insights?

<details>
<summary> versioninfo() </summary>
<code>
julia> versioninfo()
Julia Version 1.10.0-rc1
Commit 5aaa9485436 (2023-11-03 07:44 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 16 × 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, tigerlake)
  Threads: 23 on 16 virtual cores
</code>
</details>

**Comment by chriselrod** [comment]
> When updating (and bisecting) the Polyester version to the latest, I've noticed that Polyester 0.7.2 -> 0.7.3 broke my package functionality, such that the loop below maxes out my cpu but never finishes.

Not never, just very slow.

Reproducer, note the 10x smaller `M` than you used:
```julia
import SparseArrays: SparseMatrixCSC, mul!, sprand; import SparseArrays
import Polyester: @batch

function mymul!(C::AbstractMatrix, A::AbstractMatrix, B::SparseMatrixCSC, α::Number, β::Number)
    @batch for j in axes(B, 2)
        C[:, j] .*= β
        C[:, j] .+= A * (α.*B[:, j])
    end
    return C
end

N, K, M = 1_000, 2_000, 3_000;
A = rand(N, K); B = sprand(K, M, 0.05); C = similar(A, (N, M));
@time mymul!(C, A, B, true, false)
```
I get
```julia
julia> @time mymul!(C, A, B, true, false);
190.354090 seconds (2.71 M allocations: 308.822 MiB, 0.04% gc time, 1.81% compilation time)
```

**Comment by chriselrod** [comment]
0.7.2 calls `mul!`, while 0.7.3 calls `generic_matvecmul!`.

**Comment by chriselrod** [comment]
0.7.2
```julia
julia> using StrideArraysCore

julia> PtrArray(A) isa DenseArray
true
```
0.7.3
```julia
julia> PtrArray(A) isa DenseArray
false
```
Because it isn't a `DenseArray` in 0.7.3, it hits the incredibly slow fallback method.

**Comment by chriselrod** [comment]
Fixed https://github.com/JuliaSIMD/StrideArraysCore.jl/commit/afd33f218908dcc35d467002fbed212ea2b63aca
