### ISSUE TITLE
Does `@batch` wait until completion?

### ISSUE THREAD

**Issue by Socob** [JuliaSIMD/Polyester.jl#150]
I suppose it’s kind of implicit by the analogy to `Threads.@threads`, but I don’t think it’s documented anywhere that `@batch` waits until all iterations are complete on all tasks? Would be nice to mention that for completeness, as in `Threads.@threads`’ docstring:
```julia
help?> Threads.@threads
  Threads.@threads [schedule] for ... end


  A macro to execute a for loop in parallel. The iteration space is distributed to coarse-grained tasks. This policy can be specified by the
  schedule argument. The execution of the loop waits for the evaluation of all iterations.
```

**Comment by chriselrod** [comment]
It does wait.
Feel free to make a PR editing the doc string.
