### ISSUE TITLE
Rename to Polyester.jl

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaSIMD/Polyester.jl#2]
Polyester.jl: the cheapest threads you can find!

**Comment by chriselrod** [comment]
Ha, sure. Is the best way still too create a new repo, or should I make a PR against the registry?

On the subject of PRing the registry, I've also been wondering if I should move all these packages (ThreadingUtilities, CheapThreads, LoopVectorization, VectorizationBase, etc...) into an org.

**Comment by DilumAluthge** [comment]
> Ha, sure. Is the best way still too create a new repo, or should I make a PR against the registry?

For renaming a registered package, it's probably easiest to follow these steps: https://github.com/JuliaRegistries/General/blob/master/README.md#how-do-i-rename-an-existing-registered-package

**Comment by DilumAluthge** [comment]
> On the subject of PRing the registry, I've also been wondering if I should move all these packages (ThreadingUtilities, CheapThreads, LoopVectorization, VectorizationBase, etc...) into an org.

Sounds like it could be useful. Any ideas for the names of the organization? Here are some ideas:
- JuliaVectorization
- JuliaSIMD

**Comment by chriselrod** [comment]
https://github.com/JuliaSIMD/Polyester.jl/commit/a33a595579988fbcbe9f6ca49a7af1d911275613
