### ISSUE TITLE
How to customize behavior?

### ISSUE THREAD

**Issue by Moelf** [JuliaSIMD/Polyester.jl#44]
https://github.com/tamasgal/UnROOT.jl/blob/0bb8a4873331132566574e200be3573196647a81/src/iteration.jl#L199

for `@threads`, we (@aminnj really) utilized `getindex` of `Enumerate` to achieve lazy multi threading. Our object has the feature that "indices close together are stored in an indivisible on-disk chunk", so the indexing pattern of `@threads` work in our favor.

How should we go about and support Polyester? Presumably it would be more flexible because `@threads` is "just" a macro, Polyester looks like it has some functions we can overload.

**Comment by chriselrod** [comment]
The easiest way is probably through defining a `splitloop` and `combine` method.
[Here](https://github.com/JuliaSIMD/Polyester.jl/blob/f5e28d8998033283390a7a413890f8bc674e6963/src/closure.jl#L94-L124) are a few definitions it uses for `CartesianIndex` and `AbstractArray` as iterator support.

**Comment by chriselrod** [comment]
Basically, `splitloop` gets called on the iterator, returning:
1. inner iterator. If there aren't two loops (normal case), this should be `NoLoop()`.
2. outer (threaded) iterator. This one should be a range object.
3. object describing how to recombine

Later, `combine(obj3, inner, outer)` gets called, where 
1. obj3 is the third return above
2. inner is a variable that got returned by the inner iterator
3. is a variable that got returned by the outer iterator

So, like with the `AbstractArray` example, you probably want to inplement `combine` in terms of `getindex(obj3, ...)`, where obj3 is the `Enumerate` struct.
That should let you emulate `Threads.@threads`.

By modifying `ThreadingUtilities` and/or `Polyester`, it should be possible to get more specific behaviors.

These libraries are currently quite bad for unbalanced workloads. My first effort at addressing this [here](https://github.com/JuliaSIMD/ThreadingUtilities.jl/pull/34) unfortunately seemed to regress performance in some benchmarks, so I think alternative behaviors should be opt in. Just like `FLoops.jl` lets you specify the behavior you want.
