### ISSUE TITLE
Thread-local storage?

### ISSUE THREAD

**Issue by Krastanov** [JuliaSIMD/Polyester.jl#53]
This has been a pleasure to use! But now I have a loop that uses an (associative) accumulator. I would love to have multiple threads running this loop, each with its own thread-local accumulator. I can then accumulate the accumulators when the threads are done.

Is Polyester currently (or in the future) supposed to be able to do that?

How do I:
1. Calculate the number of threads that will be executed before they are executed so that I can allocate enough accumulators?
2. Get a thread id in the loop body so I can select the appropriate accumulator?

Or maybe it should be done in a different way?

**Comment by Krastanov** [comment]
This discourse thread has some suggestion for how to do this: https://discourse.julialang.org/t/questions-about-polyester-jl/68369/5

I do not know whether this issue should be counted as an enchancement-request or documentation question, but I will leave it unclosed in case anyone else has trouble finding this information.

**Comment by chriselrod** [comment]
A PR to add an API for automatically defining thread-local accumulators would be welcome.

Or if you'd like to just write your own solution, I'd take a look at `Polyester.batch`. You can look at `@macroexpand @batch ...` to get an idea of how the loops you write map to it, or look at examples [from the tests](https://github.com/JuliaSIMD/Polyester.jl/blob/master/test/runtests.jl):
```julia
function rangemap!(f::F, allargs, start, stop) where {F}
    dest = first(allargs)
    args = Base.tail(allargs)
    @inbounds @simd for i ∈ start:stop
        dest[i] = f(Base.unsafe_getindex.(args, i)...)
    end
    nothing
end

function tmap!(f::F, args::Vararg{AbstractArray,K}) where {K,F}
    dest = first(args)
    N = length(dest)
    mapfun! = (allargs, start, stop) -> rangemap!(f, allargs, start, stop)
    batch(mapfun!, (N, num_threads()), args...)
    dest
end
```
Above, the second argument (the 2-tuple) in `batch(mapfun!, (N, num_threads()), args...)` gives the total length of the iteration space, and the number of chunks. So this means you have `N` iterations divided into `Polyester.num_threads()` pieces. Thus, you'd want `num_threads()` accumulators.
The function you pass to it is then called a total of `num_threads()` times. They're given a range, indicating which of the `N` iterations they're supposed to apply to.
So you explicitly write the function operating on a chunk in this fashion.

You can also of course make `N == num_threads()`, and then manually map the chunk to the range inside that function.

**Comment by Krastanov** [comment]
Thanks, Chris, implementing this was very instructive for me and your help was greatly appreciated!

**Comment by chriselrod** [comment]
Thanks a lot for all your effort seeing this through!
