### ISSUE TITLE
Misleading documentation

### ISSUE THREAD

**Issue by carstenbauer** [JuliaSIMD/Polyester.jl#58]
The documentation of `@batch` states:

> Use at most 1 thread per physical core, or 1 thread per CPU thread, respectively.

Similar descriptions can be found in the README.md as well. 

I find this a bit misleading as it might wrongly suggest
1) that Polyester will change the number of Julia threads dynamically (in the sense that it doesn't matter with how many threads I started Julia)
2) that Polyester will do a form of thread pinning (to cores for `per=cores` and CPU threads for `per=threads`)

AFAIU, Polyester doesn't do either (please correct me if I'm worng). I would hence suggest to clarify this by mentioning that
1) Polyester can only operate with the Julia threads that are already available at startup (i.e. the `N` in `-t N` serves as a hard upper bound) and
2) that there is no form of thread pinning.

**Comment by chriselrod** [comment]
> AFAIU, Polyester doesn't do either

You are correct.
