### ISSUE TITLE
Overly strict [compat]?

### ISSUE THREAD

**Issue by eahenle** [JuliaSIMD/Polyester.jl#68]
The [compat] table in Project.toml makes it incompatible with the most recent major version of `ArrayInterface`.  This, in turn, limits compatibility with new versions of other packages.

Pinning the [compat] to a single patch of a dependency seems overly strict.  Adding `ArrayInterface v4.0.3` to the [compat] at least allows the newest version to install; after doing so, both `Polyester` and `ArrayInterface` pass their unit tests.

Is there a reason not to do this?

**Comment by chriselrod** [comment]
> Pinning the [compat] to a single patch of a dependency seems overly strict.

Specifying
```julia
ArrayInterface = "3.1.32"
```
allows any ArrayInterface version such that v"3.1.32" <= VERSION < v"4".
So it's not allowing only one specific patch.

Anyway, these tests needed to be rerun:
https://github.com/JuliaSIMD/Polyester.jl/pull/62

**Comment by eahenle** [comment]
Whoops!  I didn't realize that "^" is implicit there.  Thanks!

Also, sorry for the effective duplicate issue.  I checked the issues before posting, but not the PRs.  Glad to see you are a step ahead of me, though!

**Comment by chriselrod** [comment]
The reminder helped!
