### ISSUE TITLE
Error while calling functions with keyword arguments

### ISSUE THREAD

**Issue by sadit** [JuliaSIMD/Polyester.jl#78]
Hi,

I found an issue while calling functions with keyword arguments when working with `Polyester`  v0.6.11. A minimal example that launches the error is as follows (run with julia -t4, v1.7.2):

```julia

julia> let
          f(a; b=1.0) = a^2 + b
       
          @info "=== with @threads"
          b = 1.0
          Threads.@threads for i in 1:10
              @info f(i; b)
          end
       
          @info "=== with @batch b=b"
          @batch for i in 1:10
              @info f(i; b)
          end
       end
```

this is the output
```
[ Info: === with @threads
[ Info: 17.0
[ Info: 82.0
[ Info: 50.0
[ Info: 2.0
[ Info: 26.0
[ Info: 65.0
[ Info: 5.0
[ Info: 101.0
[ Info: 37.0
[ Info: 10.0
[ Info: === with @batch b=b
ERROR: UndefVarError: #1760#err not defined
Stacktrace:
 [1] macro expansion
   @ ~/.julia/packages/Polyester/Dx7Ws/src/closure.jl:375 [inlined]
 [2] top-level scope
   @ ./REPL[29]:11
```

Please let me know if you need another information.

**Comment by chriselrod** [comment]
I'd take a look here:
https://github.com/JuliaSIMD/Polyester.jl/blob/dddb465478ababb67318969ef2c4236e3acb3595/src/closure.jl#L132-L135

**Comment by chriselrod** [comment]
> The idea will be to create kw expressions using args[2] as the first arg and the masked name as the second arg replacing the symbol. Am I on the right track?

Yes, that sounds right to me.
