### ISSUE TITLE
Ref is converted to Ptr and it fails on getindex on dereference

### ISSUE THREAD

**Issue by sadit** [JuliaSIMD/Polyester.jl#81]
Hi, 

I found a bug while using references in @batch. A minimal function that throws the error 

```julia

julia> using Polyester

julia> function f()
         a = Ref(0.0)
         @batch for i in 1:2
             a[] += i
         end

         @assert a[] == 3
       end
f (generic function with 1 method)

julia> f()
ERROR: MethodError: no method matching getindex(::Ptr{Float64})
Closest candidates are:
  getindex(::Ref, ::CartesianIndex{0}) at ~/julia-1.7.2/share/julia/base/multidimensional.jl:1910
Stacktrace:
 [1] macro expansion
   @ ./REPL[2]:4 [inlined]
 [2] #1
   @ ~/.julia/packages/Polyester/5KrxP/src/closure.jl:289 [inlined]
 [3] macro expansion
   @ ~/.julia/packages/Polyester/5KrxP/src/batch.jl:158 [inlined]
 [4] _batch_no_reserve
   @ ~/.julia/packages/Polyester/5KrxP/src/batch.jl:111 [inlined]
 [5] batch
   @ ~/.julia/packages/Polyester/5KrxP/src/batch.jl:318 [inlined]
 [6] macro expansion
   @ ~/.julia/packages/Polyester/5KrxP/src/closure.jl:386 [inlined]
 [7] f()
   @ Main ./REPL[2]:3
 [8] top-level scope
   @ REPL[3]:1

(@v1.7) pkg> status Polyester
      Status `~/.julia/environments/v1.7/Project.toml`
  [f517fe37] Polyester v0.6.12

```

I reviewed the code and it seems that the thing comes from changing `RefValue` to `Ptr` in `StrideArraysCore` (in `object_and_preserve` function)

I just added 
```julia
import StrideArraysCore: object_and_preserve 
@inline object_and_preserve(r::Base.RefValue{T}) where {T} =  (r, r)
```

and it seems to work as expected, other tests are also ok. I am not sure the objective of changing `RefValue` as `Ptr` and if this simple fix deteriorates other use cases.

**Comment by sadit** [comment]
Despite the data race :O

```julia
  a = Ref(0.0)
  l = Threads.SpinLock()
  @batch for i in 1:2
      lock(l)
      try
        a[] += i
      finally
        unlock(l)
      end
  end

  @assert a[] == 3
```

**Comment by chriselrod** [comment]
I think you should be able to just delete that method and it should hit the fallback.

**Comment by chriselrod** [comment]
https://github.com/JuliaSIMD/StrideArraysCore.jl/commit/0f4b37f8da973199eef61fd23b93c5a6ceceda7c

**Comment by chriselrod** [comment]
Also, I didn't write the code and never tested/used/benchmarked it myself so I won't make any promises with respect to the performance, but Polyester allows defining thread local variables you can use for things like accumulations:
https://github.com/JuliaSIMD/Polyester.jl/blob/981b1e140b19a5946bba2e7005bbc7051592b820/test/runtests.jl#L281

Although be wary of false sharing, i.e. reading/writing to memory on the same cacheline.
I don't recall if the implementation actually does anything to try and avoid that.
It should really be doing something more like LoopVectorization.jl does, which also supports thread locals for reductions, but does so without any memory allocations or false sharing.

**Comment by sadit** [comment]
Thanks for the advice. In fact, I was doing "other" things with Refs and @batch and the issue arises. This is the way I reduced the issue. 

Thanks for your help!

Eric
