### ISSUE TITLE
Bounds checking with Polyester

### ISSUE THREAD

**Issue by klowrey** [JuliaSIMD/Polyester.jl#92]
I have a function that uses `@batch` to great effect, but did not realize for the longest time that inputs to that function were incorrect due to `@batch` seemingly suppressing out of bounds errors. Running the same loop without `@batch` triggers a `BoundsError`.

Is there any way to turn on bounds checking within `@batch` loops for debugging purposes without needing to edit the code to remove `@batch` macros?

**Comment by chriselrod** [comment]
I often like to start Julia with `--check-bounds=yes`.
