### ISSUE TITLE
Polyester causes significant TTFX due to dependency on `CPUSummary.num_threads()`

### ISSUE THREAD

**Issue by Krastanov** [JuliaSIMD/Polyester.jl#95]
The pkgimages support was merged into julia today: https://github.com/JuliaLang/julia/pull/47184

Even with that improvement, libraries that depend on Polyester see significant TTFX unless they run with `julia -tauto`. For instance consider the following library that depends on Polyester:

```
@time @eval QuantumClifford._precompile_() # a typical task used as a precompile directive

#with -tauto
0.037428 seconds (40.73 k allocations: ...)

#with Threads.nthreads() != Sys.CPU_THREADS
3.068928 seconds (4.78 M allocations: ...)
```

The reason for this seems to be that `CPUSummary` redefines `num_threads` in its `__init__` call as discussed in these issues:

- https://github.com/JuliaLang/julia/pull/41913
- continued in https://github.com/JuliaSIMD/CPUSummary.jl/issues/3
- an example of a fix in TriangularSolve https://github.com/JuliaSIMD/TriangularSolve.jl/pull/24
- maybe related fix in LoopVectorization https://github.com/JuliaSIMD/LoopVectorization.jl/commit/def5ad12f760f0c97817082141a77c642159f4f4

My question is **What is a reasonable path forward for improving this in Polyester?** Is one of the following reasonable:

Is not using CPUSummary in Polyester an option? I suspect the goal is to have compile-time constants when deciding on number of threads, but I do not know whether that is possible without CPUSummary.

Is it possible to improve CPUSummary to avoid this issue?

**Comment by chriselrod** [comment]
Yeah, I suggest switching to `Threads.nthreads` instead. 
PRs welcome. :)

**Comment by chriselrod** [comment]
`CPUSummary.num_threads` should be deprecated.

**Comment by Krastanov** [comment]
A first attempt at such a pull request is submitted (links above in this thread)
